#Makefile for EE450 Socket Project

all: serverA.cpp serverB.cpp serverC.cpp aws.cpp client.cpp

	g++ -std=c++11 serverA.cpp -o serverA

	g++ -std=c++11 serverB.cpp -o serverB

	g++ -std=c++11 serverC.cpp -o serverC

	g++ -std=c++11 aws.cpp -o  aws

	g++ -std=c++11 client.cpp -o client

.PHONY:serverA
serverA:
	./serverA

.PHONY:serverB
serverB: 
	./serverB

.PHONY:serverC
serverC: 
	./serverC

.PHONY:aws
aws: 
	./aws